name: Flake8 Lint

on:
  # This triggers the workflow on pull requests targeting 'dev'
  pull_request:
    branches: [ "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # or 3.9, 3.10, etc.

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 .
