name: Run Tests

on:
  pull_request:
    branches: [ "test" ]
    # This means the workflow will run whenever a Pull Request targets the 'test' branch.

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Explicitly install pytest here:
          pip install pytest
          pip install pytest numpy

      - name: Run tests
        run: |
          # Run pytest in the 'test' folder (or adjust as needed)
          pytest test
