name: Run Tests

on:
  pull_request:
    branches: [ "test" ]  # triggers when there's a PR INTO the 'test' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # If you need additional packages for testing:
          # pip install pytest joblib

      - name: Run tests
        run: |
          # Option 1: If you're using unittest:
          # python -m unittest discover

          # Option 2: If you're using pytest:
          pytest test
